#!/bin/bash

set -xe

master_hostname=`relation-get master_hostname`
master_port=`relation-get master_port`

if [[ -z $master_hostname && -z $master_port ]]
then
  echo "Redis master properties not available yet. Retry"
  exit 0
fi

port=`config-get port`

# Add master host and port in redis config and restart
sed -i.bak -e "s/\# slaveof.*/slaveof ${master_hostname} ${master_port}/" /etc/redis/$port.conf

# Check if service is already running and start or restart
if [[ `service redis_$port status` =~ "Redis is running" ]]
then
    service redis_$port restart
else
    service redis_$port start
fi

